name: GitVersion
description: Uses GitVersion to determine the next version number
outputs:
  sem-ver:
    description: The calculated sem-ver
    value: ${{ steps.gitversion.outputs.SemVer }}
runs:
  using: composite
  steps:
    - uses: gittools/actions/gitversion/setup@v4.7.0
      with:
        versionSpec: '6.x'
    - uses: gittools/actions/gitversion/execute@v4.7.0
      id: gitversion
      with:
        mode: ContinuousDeployment
